version: "3.8"

services:
  postgres-db:
    image: postgres:latest
    container_name: ancientcivexp
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ancientciv
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
