spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ancientciv
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
