CREATE TABLE site_type
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_sitetype PRIMARY KEY (id)
);

ALTER TABLE site_type
    ADD CONSTRAINT uc_sitetype_name UNIQUE (name);